# Generated by Django 3.2.8 on 2022-06-30 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
